server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bff-client
            client-secret: AF1FEWVmhmZIdtX3sZ5mCaKGizvikaqv
            scope: openid, profile, email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            # Spring сам піде за цим URL і дізнається всі ендпоінти Keycloak
            issuer-uri: http://localhost:8081/realms/bff-realm